language: ruby

script: bundle exec rake spec
install: bundle install --deployment --without debugger

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - ruby-head
notifications:
  email:
    recipients:
      - niklaus.giger@member.fsf.org

