language: ruby

sudo: false

cache: bundler

script:
  - bundle exec rspec
  - bundle exec rake install

install: bundle install --deployment --without debugger

rvm:
#  - 2.2.x or earlier cannot run because mediawiki-butt requires at least Ruby 2.3
  - 2.3.4
  - 2.4.1
  - 2.5.0

matrix:
  allow_failures:
    - rvm: 2.3.4
    - rvm: 2.1.2

notifications:
  email:
    recipients:
      - niklaus.giger@member.fsf.org

