language: ruby

sudo: false

cache: bundler

script:
  - bundle exec rspec
  - bundle exec rake install

install: bundle install --deployment --without debugger

rvm:
#  - 1.8.7 cannot run on ruby 1.8 because mediawiki-gateway requires at least Ruby 1.9
  - 1.9.3
  - 2.1.2
  - 2.2.0

matrix:
  allow_failures:
    - rvm: 2.2.0
    - rvm: 2.1.2

notifications:
  email:
    recipients:
      - niklaus.giger@member.fsf.org

